name: juliobevione.net
favicon: null
layout_spectrum: 0.37049792474135756
typography_spectrum: 0.9885160170961171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9395957586821169
  lightness: 0.08783199125900865
  saturation: 0.8260093065910041
  rhythmicContrast: 0.876789627596736
purpose: []
